package net.peterd.zombierun.game;

public enum GameEvent {
  GAME_START,
  GAME_PAUSE,
  GAME_RESUME,
  GAME_WIN,
  GAME_LOSE,
  GAME_QUIT,
  
  ZOMBIE_NOTICE_PLAYER,
  ZOMBIE_NEAR_PLAYER,
  ZOMBIE_CATCH_PLAYER,
  PLAYER_REACHES_DESTINATION,
  
  UPDATED_ZOMBIE_LOCATIONS,
  UPDATED_PLAYER_LOCATIONS,
}
