application: zombie-run-game-server
version: 1
runtime: python
api_version: 1

default_expiration: "7d"

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /res
  static_dir: static/res
- url: /favicon.ico
  static_files: static/res/favicon.ico
  upload: static/res/favicon.ico
- url: /tasks/.*
  script: main.py
  login: admin
- url: /.*
  script: main.py